name: Sync upstream release

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"   # 每天 10:30 北京时间执行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release info
        id: latest
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          repository: maitel2020/wtv

      - name: Download release assets
        uses: dsaltares/fetch-gh-release-asset@v1
        with:
          repo: maitel2020/wtv
          version: ${{ steps.latest.outputs.release }}
          file: "*"

      - name: Publish to my repo
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.latest.outputs.release }}
          name: "wtv ${{ steps.latest.outputs.release }}"
          files: |
            ./*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
